
all: 
		gcc xboard.c arora.c uci.c evaluate.c pvtable.c init.c bitboard.c hashkey.c board.c data.c attack.c io.c movegen.c validation.c makemove.c perft.c search.c misc.c polybook.c polykeys.c -o arora 
 